## generated by : /public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.0.4/venv-bin-v2.0.4/bin/cactus-prepare --wdl ./ucsc_birds_scaled_consensus.txt --noLocalInputs --preprocessBatchSize 10 --alignDisk 3000G --halAppendDisk 3000G --preprocessDisk 3000G --defaultDisk 1000G --defaultCores 64 --gpu --gpuCount 8 --defaultMemory 385G --configFile ./cactus_progressive_config.xml
## date : 2021-12-28 08:41:01.194864
## cactus commit : eca7219f3943465b73f240dd86b5e8e228162144

version 1.0

task cactus_preprocess {
    input {
        Array[File]? in_files
        Array[String]? in_urls
        File? in_config_file
        Array[String] out_names
    }
    command {
        cactus-preprocess /mnt/hdd/jobstore --inPaths ${sep=" " default="" in_files} ${sep=" " default="" in_urls} --outPaths ${sep=" " out_names} --realTimeLogging --logInfo --retryCount 0 --maxCores 64 --workDir /mnt/hdd ${"--configFile " + in_config_file}
    }
    runtime {
        preemptible: 2
        cpu: 64
        memory: "358GB"
        disks: "local-disk 300 LOCAL, /mnt/hdd 2793 HDD"
        gpuType: "nvidia-tesla-v100"
        gpuCount: 8
        bootDiskSizeGb: 20
        nvidiaDriverVersion: "440.64.00"
        docker: "quay.io/comparative-genomics-toolkit/cactus:v2.0.4-gpu"
        zones: "us-central1-a"
    }
    output {
        Array[File] out_files=out_names
    }
}

task cactus_blast {
    input {
        File in_seq_file
        Array[String] in_fa_names
        Array[File] in_fa_files
        String in_root
        File? in_config_file
        String out_name
    }
    command {
        cactus-blast /mnt/hdd/jobstore ${in_seq_file} ${out_name} --root ${in_root} --pathOverrides ${sep=" " in_fa_files} --pathOverrideNames ${sep=" " in_fa_names} --realTimeLogging --logInfo --retryCount 0 --maxCores 64 --workDir /mnt/hdd ${"--configFile " + in_config_file}
    }
    runtime {
        preemptible: 2
        maxRetries: 2		
        cpu: 64
        memory: "358GB"
        disks: "local-disk 300 LOCAL, /mnt/hdd 931 HDD"
        gpuType: "nvidia-tesla-v100"
        gpuCount: 8
        bootDiskSizeGb: 20
        nvidiaDriverVersion: "440.64.00"
        docker: "quay.io/comparative-genomics-toolkit/cactus:v2.0.4-gpu"
        zones: "us-central1-a"
    }
    output {
        Array[File] out_files=glob("${out_name}*")
    }
}

task cactus_align {
    input {
        File in_seq_file
        Array[String] in_fa_names
        Array[File] in_fa_files
        Array[File] in_blast_files
        String in_root
        File? in_config_file
        String out_hal_name
        String out_fa_name
    }
    command {
        cactus-align /mnt/hdd/jobstore ${in_seq_file} ${sep=" " in_blast_files} ${out_hal_name} --root ${in_root} --pathOverrides ${sep=" " in_fa_files} --pathOverrideNames ${sep=" " in_fa_names} --realTimeLogging --logInfo --retryCount 0 --maxCores 64 --workDir /mnt/hdd ${"--configFile " + in_config_file}
        hal2fasta ${out_hal_name} ${in_root} --hdf5InMemory > ${out_fa_name}
    }
    runtime {
        docker: "quay.io/comparative-genomics-toolkit/cactus:eca7219f3943465b73f240dd86b5e8e228162144"
        preemptible: 1
        cpu: 64
        memory: "358GB"
        disks: "local-disk 300 LOCAL, /mnt/hdd 2793 HDD"
        zones: "us-west2-a"
    }
    output {
        File out_hal_file="${out_hal_name}"
        File out_fa_file="${out_fa_name}"
    }
}

task hal_append_subtree {
    input {
        File in_hal_parent
        File in_hal_child
        String in_name
    }
    String parent_name = basename("${in_hal_parent}")
    command {
        cp ${in_hal_parent} /mnt/hdd/${parent_name}
        halAppendSubtree /mnt/hdd/${parent_name} ${in_hal_child} ${in_name} ${in_name} --merge --hdf5InMemory
    }
    runtime {
        docker: "quay.io/comparative-genomics-toolkit/cactus:eca7219f3943465b73f240dd86b5e8e228162144"
        preemptible: 1
        cpu: 1
        memory: "358GB"
        disks: "local-disk 300 LOCAL, /mnt/hdd 2793 HDD"
        zones: "us-west2-a"
    }
    output {
        File out_file="/mnt/hdd/${parent_name}"
    }
}

workflow cactus_prepared {

    input {
        File seq_file
        File? config_file
    }

## Preprocessor
    call cactus_preprocess as preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e {
        input: in_urls=["http://public.gi.ucsc.edu/~hickey/birds/GCA_009819545.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_015237465.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_016128335.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009819775.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_009769625.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_905368555.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009769525.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_901699155.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_017976375.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009769465.1.fa"], in_config_file=config_file, out_names=["GCA_009819545.1.fa.pp", "GCF_015237465.2.fa.pp", "GCA_016128335.1.fa.pp", "GCA_009819775.1.fa.pp", "GCF_009769625.2.fa.pp", "GCA_905368555.1.fa.pp", "GCA_009769525.1.fa.pp", "GCA_901699155.2.fa.pp", "GCA_017976375.1.fa.pp", "GCA_009769465.1.fa.pp"]
    }
    call cactus_preprocess as preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17 {
        input: in_urls=["http://public.gi.ucsc.edu/~hickey/birds/GCA_907165065.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_017639555.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_020745775.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_015476345.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_009819795.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/galGal6.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_013368605.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_011004875.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_020800305.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_017639485.1.fa"], in_config_file=config_file, out_names=["GCA_907165065.1.fa.pp", "GCA_017639555.1.fa.pp", "GCA_020745775.1.fa.pp", "GCF_015476345.1.fa.pp", "GCF_009819795.1.fa.pp", "galGal6.fa.pp", "GCA_013368605.1.fa.pp", "GCA_011004875.1.fa.pp", "GCA_020800305.1.fa.pp", "GCA_017639485.1.fa.pp"]
    }
    call cactus_preprocess as preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf {
        input: in_urls=["http://public.gi.ucsc.edu/~hickey/birds/GCA_009819825.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_016699485.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_016700215.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_003957555.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_008658365.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009819605.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_900496995.4.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_018139145.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_020746105.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_020740795.1.fa"], in_config_file=config_file, out_names=["GCA_009819825.1.fa.pp", "GCF_016699485.2.fa.pp", "GCF_016700215.1.fa.pp", "GCF_003957555.1.fa.pp", "GCA_008658365.1.fa.pp", "GCA_009819605.1.fa.pp", "GCF_900496995.4.fa.pp", "GCA_018139145.1.fa.pp", "GCA_020746105.1.fa.pp", "GCA_020740795.1.fa.pp"]
    }
    call cactus_preprocess as preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11 {
        input: in_urls=["http://public.gi.ucsc.edu/~hickey/birds/GCA_020745705.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009769605.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_017639655.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_015220075.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009819595.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_004027225.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_016904835.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_014839835.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_015220805.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_012275295.1.fa"], in_config_file=config_file, out_names=["GCA_020745705.1.fa.pp", "GCA_009769605.1.fa.pp", "GCF_017639655.2.fa.pp", "GCF_015220075.1.fa.pp", "GCA_009819595.1.fa.pp", "GCF_004027225.2.fa.pp", "GCA_016904835.1.fa.pp", "GCA_014839835.1.fa.pp", "GCA_015220805.1.fa.pp", "GCF_012275295.1.fa.pp"]
    }
    call cactus_preprocess as preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857 {
        input: in_urls=["http://public.gi.ucsc.edu/~hickey/birds/GCA_017639245.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_009829145.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_013407035.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_020740725.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_015227805.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_000738735.5.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_009650955.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009819655.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_014839755.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_009819885.2.fa"], in_config_file=config_file, out_names=["GCA_017639245.1.fa.pp", "GCF_009829145.1.fa.pp", "GCA_013407035.1.fa.pp", "GCA_020740725.1.fa.pp", "GCF_015227805.1.fa.pp", "GCF_000738735.5.fa.pp", "GCF_009650955.1.fa.pp", "GCA_009819655.1.fa.pp", "GCA_014839755.1.fa.pp", "GCF_009819885.2.fa.pp"]
    }
    call cactus_preprocess as preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5 {
        input: in_urls=["http://public.gi.ucsc.edu/~hickey/birds/GCA_903797595.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_003957565.2.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_015832195.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_902806625.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_019023105.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCA_009764595.1.fa", "http://public.gi.ucsc.edu/~hickey/birds/GCF_012460135.1.fa"], in_config_file=config_file, out_names=["GCA_903797595.2.fa.pp", "GCF_003957565.2.fa.pp", "GCF_015832195.1.fa.pp", "GCA_902806625.1.fa.pp", "GCA_019023105.1.fa.pp", "GCA_009764595.1.fa.pp", "GCF_012460135.1.fa.pp"]
    }

## Alignment

### Round 0
    call cactus_blast as blast_BirdsAnc08 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_009769525.1_bPteGut1.pri", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6", "GCA_901699155.2_bStrTur1.1"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[6], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[7]], in_root="BirdsAnc08", in_config_file=config_file, out_name="BirdsAnc08.cigar"
    }
    call cactus_align as align_BirdsAnc08 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_009769525.1_bPteGut1.pri", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6", "GCA_901699155.2_bStrTur1.1"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[6], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[7]], in_blast_files=blast_BirdsAnc08.out_files, in_root="BirdsAnc08", in_config_file=config_file, out_hal_name="BirdsAnc08.hal", out_fa_name="BirdsAnc08.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc09 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_017976375.1_bCucCan1.pri", "GCF_000002315.5_GalGal6", "GCA_017639555.1_bCicMag1.pri", "GCA_009769465.1_bTauEry1.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[9]], in_root="BirdsAnc09", in_config_file=config_file, out_name="BirdsAnc09.cigar"
    }
    call cactus_align as align_BirdsAnc09 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_017976375.1_bCucCan1.pri", "GCF_000002315.5_GalGal6", "GCA_017639555.1_bCicMag1.pri", "GCA_009769465.1_bTauEry1.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[9]], in_blast_files=blast_BirdsAnc09.out_files, in_root="BirdsAnc09", in_config_file=config_file, out_hal_name="BirdsAnc09.hal", out_fa_name="BirdsAnc09.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc12 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_020745775.1_bTheCae1.pri.cur", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6", "GCA_009819775.1_bPhoRub2.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[3]], in_root="BirdsAnc12", in_config_file=config_file, out_name="BirdsAnc12.cigar"
    }
    call cactus_align as align_BirdsAnc12 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_020745775.1_bTheCae1.pri.cur", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6", "GCA_009819775.1_bPhoRub2.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[3]], in_blast_files=blast_BirdsAnc12.out_files, in_root="BirdsAnc12", in_config_file=config_file, out_hal_name="BirdsAnc12.hal", out_fa_name="BirdsAnc12.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc14 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCF_009819795.1_bAytFul2.pri", "GCF_009769625.2_bCygOlo1.pri.v2", "GCF_000002315.5_GalGal6", "GCF_015476345.1_ZJU1.0"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[4], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[3]], in_root="BirdsAnc14", in_config_file=config_file, out_name="BirdsAnc14.cigar"
    }
    call cactus_align as align_BirdsAnc14 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCF_009819795.1_bAytFul2.pri", "GCF_009769625.2_bCygOlo1.pri.v2", "GCF_000002315.5_GalGal6", "GCF_015476345.1_ZJU1.0"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[4], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[3]], in_blast_files=blast_BirdsAnc14.out_files, in_root="BirdsAnc14", in_config_file=config_file, out_hal_name="BirdsAnc14.hal", out_fa_name="BirdsAnc14.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc17 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_011004875.1_bBalReg1.pri", "GCA_020800305.1_bPorHoc1.mat.Z.cur", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5]], in_root="BirdsAnc17", in_config_file=config_file, out_name="BirdsAnc17.cigar"
    }
    call cactus_align as align_BirdsAnc17 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_011004875.1_bBalReg1.pri", "GCA_020800305.1_bPorHoc1.mat.Z.cur", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5]], in_blast_files=blast_BirdsAnc17.out_files, in_root="BirdsAnc17", in_config_file=config_file, out_hal_name="BirdsAnc17.hal", out_fa_name="BirdsAnc17.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc21 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_016700215.1_bGalGal1.pat.whiteleghornlayer.GRCg7w", "GCF_009769625.2_bCygOlo1.pri.v2", "GCF_000002315.5_GalGal6", "GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b", "GCA_905368555.1_MGAL_WU_HG_1.0"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[2], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[5]], in_root="BirdsAnc21", in_config_file=config_file, out_name="BirdsAnc21.cigar"
    }
    call cactus_align as align_BirdsAnc21 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_016700215.1_bGalGal1.pat.whiteleghornlayer.GRCg7w", "GCF_009769625.2_bCygOlo1.pri.v2", "GCF_000002315.5_GalGal6", "GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b", "GCA_905368555.1_MGAL_WU_HG_1.0"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[2], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[5]], in_blast_files=blast_BirdsAnc21.out_files, in_root="BirdsAnc21", in_config_file=config_file, out_hal_name="BirdsAnc21.hal", out_fa_name="BirdsAnc21.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc23 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_009819605.1_bSteHir1.pri", "GCA_008658365.1_bAlcTor1_primary", "GCF_000002315.5_GalGal6", "GCA_017639485.1_bPluApr1.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[5], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[9]], in_root="BirdsAnc23", in_config_file=config_file, out_name="BirdsAnc23.cigar"
    }
    call cactus_align as align_BirdsAnc23 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_009819605.1_bSteHir1.pri", "GCA_008658365.1_bAlcTor1_primary", "GCF_000002315.5_GalGal6", "GCA_017639485.1_bPluApr1.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[5], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[9]], in_blast_files=blast_BirdsAnc23.out_files, in_root="BirdsAnc23", in_config_file=config_file, out_hal_name="BirdsAnc23.hal", out_fa_name="BirdsAnc23.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc24 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_020745775.1_bTheCae1.pri.cur", "GCF_000002315.5_GalGal6", "GCA_017639555.1_bCicMag1.pri", "GCF_900496995.4_bAquChr1.4"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[6]], in_root="BirdsAnc24", in_config_file=config_file, out_name="BirdsAnc24.cigar"
    }
    call cactus_align as align_BirdsAnc24 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_020745775.1_bTheCae1.pri.cur", "GCF_000002315.5_GalGal6", "GCA_017639555.1_bCicMag1.pri", "GCF_900496995.4_bAquChr1.4"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[6]], in_blast_files=blast_BirdsAnc24.out_files, in_root="BirdsAnc24", in_config_file=config_file, out_hal_name="BirdsAnc24.hal", out_fa_name="BirdsAnc24.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc27 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_020740795.1_bApuApu2.pri.cur", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6", "GCA_020745705.1_bHemCom1.pri.cur"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[9], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[0]], in_root="BirdsAnc27", in_config_file=config_file, out_name="BirdsAnc27.cigar"
    }
    call cactus_align as align_BirdsAnc27 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_020740795.1_bApuApu2.pri.cur", "GCA_017639555.1_bCicMag1.pri", "GCF_000002315.5_GalGal6", "GCA_020745705.1_bHemCom1.pri.cur"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[9], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[0]], in_blast_files=blast_BirdsAnc27.out_files, in_root="BirdsAnc27", in_config_file=config_file, out_hal_name="BirdsAnc27.hal", out_fa_name="BirdsAnc27.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc29 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCF_017639655.2_bFalNau1.pat", "GCF_015220075.1_bFalRus1.pri", "GCF_000002315.5_GalGal6", "GCF_900496995.4_bAquChr1.4"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[2], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[3], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[6]], in_root="BirdsAnc29", in_config_file=config_file, out_name="BirdsAnc29.cigar"
    }
    call cactus_align as align_BirdsAnc29 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCF_017639655.2_bFalNau1.pat", "GCF_015220075.1_bFalRus1.pri", "GCF_000002315.5_GalGal6", "GCF_900496995.4_bAquChr1.4"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[2], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[3], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[6]], in_blast_files=blast_BirdsAnc29.out_files, in_root="BirdsAnc29", in_config_file=config_file, out_hal_name="BirdsAnc29.hal", out_fa_name="BirdsAnc29.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc34 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_014839835.1_bDryPub1.pri", "GCF_000002315.5_GalGal6", "GCA_015220805.1_bPogPus1.pri", "GCF_900496995.4_bAquChr1.4"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[8], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[6]], in_root="BirdsAnc34", in_config_file=config_file, out_name="BirdsAnc34.cigar"
    }
    call cactus_align as align_BirdsAnc34 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_014839835.1_bDryPub1.pri", "GCF_000002315.5_GalGal6", "GCA_015220805.1_bPogPus1.pri", "GCF_900496995.4_bAquChr1.4"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[7], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[8], preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[6]], in_blast_files=blast_BirdsAnc34.out_files, in_root="BirdsAnc34", in_config_file=config_file, out_hal_name="BirdsAnc34.hal", out_fa_name="BirdsAnc34.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc35 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_017639245.1_MMon_1.0", "GCF_000002315.5_GalGal6", "GCF_012275295.1_bMelUnd1.mat.Z", "GCF_004027225.2_bStrHab1.2.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[0], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[9], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[5]], in_root="BirdsAnc35", in_config_file=config_file, out_name="BirdsAnc35.cigar"
    }
    call cactus_align as align_BirdsAnc35 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_018139145.1_ASM1813914v1", "GCA_017639245.1_MMon_1.0", "GCF_000002315.5_GalGal6", "GCF_012275295.1_bMelUnd1.mat.Z", "GCF_004027225.2_bStrHab1.2.pri"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[7], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[0], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[9], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[5]], in_blast_files=blast_BirdsAnc35.out_files, in_root="BirdsAnc35", in_config_file=config_file, out_hal_name="BirdsAnc35.hal", out_fa_name="BirdsAnc35.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc43 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_020740725.1_bCorHaw1.pri.cur", "GCF_000738735.5_ASM73873v5", "GCF_000002315.5_GalGal6", "GCA_013407035.1_ASM1340703v1", "GCF_009650955.1_bCorMon1.pri"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[3], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[2], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[6]], in_root="BirdsAnc43", in_config_file=config_file, out_name="BirdsAnc43.cigar"
    }
    call cactus_align as align_BirdsAnc43 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_020740725.1_bCorHaw1.pri.cur", "GCF_000738735.5_ASM73873v5", "GCF_000002315.5_GalGal6", "GCA_013407035.1_ASM1340703v1", "GCF_009650955.1_bCorMon1.pri"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[3], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[2], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[6]], in_blast_files=blast_BirdsAnc43.out_files, in_root="BirdsAnc43", in_config_file=config_file, out_hal_name="BirdsAnc43.hal", out_fa_name="BirdsAnc43.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc44 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819655.1_bSylAtr1.pri", "GCF_015227805.1_bHirRus1.pri.v2", "GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCA_014839755.1_bSylBor1.pri", "GCF_000002315.5_GalGal6"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[7], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[4], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5]], in_root="BirdsAnc44", in_config_file=config_file, out_name="BirdsAnc44.cigar"
    }
    call cactus_align as align_BirdsAnc44 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819655.1_bSylAtr1.pri", "GCF_015227805.1_bHirRus1.pri.v2", "GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCA_014839755.1_bSylBor1.pri", "GCF_000002315.5_GalGal6"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[7], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[4], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5]], in_blast_files=blast_BirdsAnc44.out_files, in_root="BirdsAnc44", in_config_file=config_file, out_hal_name="BirdsAnc44.hal", out_fa_name="BirdsAnc44.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc45 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_009819885.2_bCatUst1.pri.v2", "GCA_903797595.2_bEriRub2.2", "GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCA_019023105.1_LSU_DiBr_2.0", "GCF_000002315.5_GalGal6"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[9], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[0], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5]], in_root="BirdsAnc45", in_config_file=config_file, out_name="BirdsAnc45.cigar"
    }
    call cactus_align as align_BirdsAnc45 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_009819885.2_bCatUst1.pri.v2", "GCA_903797595.2_bEriRub2.2", "GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCA_019023105.1_LSU_DiBr_2.0", "GCF_000002315.5_GalGal6"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[9], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[0], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5]], in_blast_files=blast_BirdsAnc45.out_files, in_root="BirdsAnc45", in_config_file=config_file, out_hal_name="BirdsAnc45.hal", out_fa_name="BirdsAnc45.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc49 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_902806625.1_Camarhynchus_parvulus_V1.1", "GCF_012460135.1_BPBGC_Mater_1.0", "GCA_019023105.1_LSU_DiBr_2.0", "GCF_000002315.5_GalGal6", "GCA_009764595.1_bGeoTri1.pri"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[3], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[6], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[5]], in_root="BirdsAnc49", in_config_file=config_file, out_name="BirdsAnc49.cigar"
    }
    call cactus_align as align_BirdsAnc49 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_902806625.1_Camarhynchus_parvulus_V1.1", "GCF_012460135.1_BPBGC_Mater_1.0", "GCA_019023105.1_LSU_DiBr_2.0", "GCF_000002315.5_GalGal6", "GCA_009764595.1_bGeoTri1.pri"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[3], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[6], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[5]], in_blast_files=blast_BirdsAnc49.out_files, in_root="BirdsAnc49", in_config_file=config_file, out_hal_name="BirdsAnc49.hal", out_fa_name="BirdsAnc49.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc50 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_902806625.1_Camarhynchus_parvulus_V1.1", "GCF_012460135.1_BPBGC_Mater_1.0", "GCA_019023105.1_LSU_DiBr_2.0", "GCF_000002315.5_GalGal6", "GCA_009764595.1_bGeoTri1.pri"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[3], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[6], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[5]], in_root="BirdsAnc50", in_config_file=config_file, out_name="BirdsAnc50.cigar"
    }
    call cactus_align as align_BirdsAnc50 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_902806625.1_Camarhynchus_parvulus_V1.1", "GCF_012460135.1_BPBGC_Mater_1.0", "GCA_019023105.1_LSU_DiBr_2.0", "GCF_000002315.5_GalGal6", "GCA_009764595.1_bGeoTri1.pri"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[3], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[6], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[5]], in_blast_files=blast_BirdsAnc50.out_files, in_root="BirdsAnc50", in_config_file=config_file, out_hal_name="BirdsAnc50.hal", out_fa_name="BirdsAnc50.fa.pp"
    }

### Round 1
    call cactus_blast as blast_BirdsAnc06 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_009769625.2_bCygOlo1.pri.v2", "GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc09", "BirdsAnc14"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc09.out_fa_file, align_BirdsAnc14.out_fa_file], in_root="BirdsAnc06", in_config_file=config_file, out_name="BirdsAnc06.cigar"
    }
    call cactus_align as align_BirdsAnc06 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_009769625.2_bCygOlo1.pri.v2", "GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc09", "BirdsAnc14"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc09.out_fa_file, align_BirdsAnc14.out_fa_file], in_blast_files=blast_BirdsAnc06.out_files, in_root="BirdsAnc06", in_config_file=config_file, out_hal_name="BirdsAnc06.hal", out_fa_name="BirdsAnc06.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc15 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_905368555.1_MGAL_WU_HG_1.0", "BirdsAnc08", "BirdsAnc21", "BirdsAnc09"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc21.out_fa_file, align_BirdsAnc09.out_fa_file], in_root="BirdsAnc15", in_config_file=config_file, out_name="BirdsAnc15.cigar"
    }
    call cactus_align as align_BirdsAnc15 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_905368555.1_MGAL_WU_HG_1.0", "BirdsAnc08", "BirdsAnc21", "BirdsAnc09"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc21.out_fa_file, align_BirdsAnc09.out_fa_file], in_blast_files=blast_BirdsAnc15.out_files, in_root="BirdsAnc15", in_config_file=config_file, out_hal_name="BirdsAnc15.hal", out_fa_name="BirdsAnc15.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc18 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_017639485.1_bPluApr1.pri", "BirdsAnc23", "BirdsAnc08", "BirdsAnc09"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[9], align_BirdsAnc23.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc09.out_fa_file], in_root="BirdsAnc18", in_config_file=config_file, out_name="BirdsAnc18.cigar"
    }
    call cactus_align as align_BirdsAnc18 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_017639485.1_bPluApr1.pri", "BirdsAnc23", "BirdsAnc08", "BirdsAnc09"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[9], align_BirdsAnc23.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc09.out_fa_file], in_blast_files=blast_BirdsAnc18.out_files, in_root="BirdsAnc18", in_config_file=config_file, out_hal_name="BirdsAnc18.hal", out_fa_name="BirdsAnc18.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc22 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_003957555.1_bCalAnn1_v1.p", "GCF_000002315.5_GalGal6", "BirdsAnc27", "BirdsAnc08", "BirdsAnc09"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[3], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc27.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc09.out_fa_file], in_root="BirdsAnc22", in_config_file=config_file, out_name="BirdsAnc22.cigar"
    }
    call cactus_align as align_BirdsAnc22 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_003957555.1_bCalAnn1_v1.p", "GCF_000002315.5_GalGal6", "BirdsAnc27", "BirdsAnc08", "BirdsAnc09"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[3], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc27.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc09.out_fa_file], in_blast_files=blast_BirdsAnc22.out_files, in_root="BirdsAnc22", in_config_file=config_file, out_hal_name="BirdsAnc22.hal", out_fa_name="BirdsAnc22.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc31 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819595.1_bMerNub1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc34", "BirdsAnc08", "BirdsAnc24"], in_fa_files=[preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc34.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file], in_root="BirdsAnc31", in_config_file=config_file, out_name="BirdsAnc31.cigar"
    }
    call cactus_align as align_BirdsAnc31 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819595.1_bMerNub1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc34", "BirdsAnc08", "BirdsAnc24"], in_fa_files=[preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc34.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file], in_blast_files=blast_BirdsAnc31.out_files, in_root="BirdsAnc31", in_config_file=config_file, out_hal_name="BirdsAnc31.hal", out_fa_name="BirdsAnc31.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc32 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCF_004027225.2_bStrHab1.2.pri", "BirdsAnc35", "BirdsAnc08", "BirdsAnc24"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[5], align_BirdsAnc35.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file], in_root="BirdsAnc32", in_config_file=config_file, out_name="BirdsAnc32.cigar"
    }
    call cactus_align as align_BirdsAnc32 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCF_004027225.2_bStrHab1.2.pri", "BirdsAnc35", "BirdsAnc08", "BirdsAnc24"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[5], align_BirdsAnc35.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file], in_blast_files=blast_BirdsAnc32.out_files, in_root="BirdsAnc32", in_config_file=config_file, out_hal_name="BirdsAnc32.hal", out_fa_name="BirdsAnc32.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc40 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_020740725.1_bCorHaw1.pri.cur", "GCF_000002315.5_GalGal6", "GCA_013407035.1_ASM1340703v1", "BirdsAnc43", "BirdsAnc45"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[3], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[2], align_BirdsAnc43.out_fa_file, align_BirdsAnc45.out_fa_file], in_root="BirdsAnc40", in_config_file=config_file, out_name="BirdsAnc40.cigar"
    }
    call cactus_align as align_BirdsAnc40 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_020740725.1_bCorHaw1.pri.cur", "GCF_000002315.5_GalGal6", "GCA_013407035.1_ASM1340703v1", "BirdsAnc43", "BirdsAnc45"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[3], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[2], align_BirdsAnc43.out_fa_file, align_BirdsAnc45.out_fa_file], in_blast_files=blast_BirdsAnc40.out_files, in_root="BirdsAnc40", in_config_file=config_file, out_hal_name="BirdsAnc40.hal", out_fa_name="BirdsAnc40.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc41 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015227805.1_bHirRus1.pri.v2", "GCF_000002315.5_GalGal6", "BirdsAnc44", "BirdsAnc50", "BirdsAnc45"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc44.out_fa_file, align_BirdsAnc50.out_fa_file, align_BirdsAnc45.out_fa_file], in_root="BirdsAnc41", in_config_file=config_file, out_name="BirdsAnc41.cigar"
    }
    call cactus_align as align_BirdsAnc41 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015227805.1_bHirRus1.pri.v2", "GCF_000002315.5_GalGal6", "BirdsAnc44", "BirdsAnc50", "BirdsAnc45"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[4], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc44.out_fa_file, align_BirdsAnc50.out_fa_file, align_BirdsAnc45.out_fa_file], in_blast_files=blast_BirdsAnc41.out_files, in_root="BirdsAnc41", in_config_file=config_file, out_hal_name="BirdsAnc41.hal", out_fa_name="BirdsAnc41.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc48 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCF_000002315.5_GalGal6", "BirdsAnc49", "BirdsAnc50", "BirdsAnc45"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc49.out_fa_file, align_BirdsAnc50.out_fa_file, align_BirdsAnc45.out_fa_file], in_root="BirdsAnc48", in_config_file=config_file, out_name="BirdsAnc48.cigar"
    }
    call cactus_align as align_BirdsAnc48 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCF_000002315.5_GalGal6", "BirdsAnc49", "BirdsAnc50", "BirdsAnc45"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc49.out_fa_file, align_BirdsAnc50.out_fa_file, align_BirdsAnc45.out_fa_file], in_blast_files=blast_BirdsAnc48.out_files, in_root="BirdsAnc48", in_config_file=config_file, out_hal_name="BirdsAnc48.hal", out_fa_name="BirdsAnc48.fa.pp"
    }

### Round 2
    call cactus_blast as blast_BirdsAnc07 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_905368555.1_MGAL_WU_HG_1.0", "BirdsAnc15", "BirdsAnc08", "BirdsAnc06", "BirdsAnc09"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[5], align_BirdsAnc15.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc06.out_fa_file, align_BirdsAnc09.out_fa_file], in_root="BirdsAnc07", in_config_file=config_file, out_name="BirdsAnc07.cigar"
    }
    call cactus_align as align_BirdsAnc07 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_905368555.1_MGAL_WU_HG_1.0", "BirdsAnc15", "BirdsAnc08", "BirdsAnc06", "BirdsAnc09"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[5], align_BirdsAnc15.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc06.out_fa_file, align_BirdsAnc09.out_fa_file], in_blast_files=blast_BirdsAnc07.out_files, in_root="BirdsAnc07", in_config_file=config_file, out_hal_name="BirdsAnc07.hal", out_fa_name="BirdsAnc07.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc11 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc17", "BirdsAnc09", "BirdsAnc18"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc17.out_fa_file, align_BirdsAnc09.out_fa_file, align_BirdsAnc18.out_fa_file], in_root="BirdsAnc11", in_config_file=config_file, out_name="BirdsAnc11.cigar"
    }
    call cactus_align as align_BirdsAnc11 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc17", "BirdsAnc09", "BirdsAnc18"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc17.out_fa_file, align_BirdsAnc09.out_fa_file, align_BirdsAnc18.out_fa_file], in_blast_files=blast_BirdsAnc11.out_files, in_root="BirdsAnc11", in_config_file=config_file, out_hal_name="BirdsAnc11.hal", out_fa_name="BirdsAnc11.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc16 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_013368605.1_bNycGra1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc22", "BirdsAnc09"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[6], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc22.out_fa_file, align_BirdsAnc09.out_fa_file], in_root="BirdsAnc16", in_config_file=config_file, out_name="BirdsAnc16.cigar"
    }
    call cactus_align as align_BirdsAnc16 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_013368605.1_bNycGra1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc22", "BirdsAnc09"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[6], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc22.out_fa_file, align_BirdsAnc09.out_fa_file], in_blast_files=blast_BirdsAnc16.out_files, in_root="BirdsAnc16", in_config_file=config_file, out_hal_name="BirdsAnc16.hal", out_fa_name="BirdsAnc16.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc28 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_009769605.1_bBucAby1.pri", "BirdsAnc08", "BirdsAnc24", "BirdsAnc31"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[1], align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file, align_BirdsAnc31.out_fa_file], in_root="BirdsAnc28", in_config_file=config_file, out_name="BirdsAnc28.cigar"
    }
    call cactus_align as align_BirdsAnc28 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_009769605.1_bBucAby1.pri", "BirdsAnc08", "BirdsAnc24", "BirdsAnc31"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[1], align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file, align_BirdsAnc31.out_fa_file], in_blast_files=blast_BirdsAnc28.out_files, in_root="BirdsAnc28", in_config_file=config_file, out_hal_name="BirdsAnc28.hal", out_fa_name="BirdsAnc28.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc38 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_013407035.1_ASM1340703v1", "BirdsAnc41", "BirdsAnc45", "BirdsAnc40"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[2], align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file, align_BirdsAnc40.out_fa_file], in_root="BirdsAnc38", in_config_file=config_file, out_name="BirdsAnc38.cigar"
    }
    call cactus_align as align_BirdsAnc38 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_013407035.1_ASM1340703v1", "BirdsAnc41", "BirdsAnc45", "BirdsAnc40"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[2], align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file, align_BirdsAnc40.out_fa_file], in_blast_files=blast_BirdsAnc38.out_files, in_root="BirdsAnc38", in_config_file=config_file, out_hal_name="BirdsAnc38.hal", out_fa_name="BirdsAnc38.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc47 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCF_000002315.5_GalGal6", "BirdsAnc48", "BirdsAnc41", "BirdsAnc45"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc48.out_fa_file, align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file], in_root="BirdsAnc47", in_config_file=config_file, out_name="BirdsAnc47.cigar"
    }
    call cactus_align as align_BirdsAnc47 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015832195.1_Motacilla_alba_V1.0_pri", "GCF_000002315.5_GalGal6", "BirdsAnc48", "BirdsAnc41", "BirdsAnc45"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc48.out_fa_file, align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file], in_blast_files=blast_BirdsAnc47.out_files, in_root="BirdsAnc47", in_config_file=config_file, out_hal_name="BirdsAnc47.hal", out_fa_name="BirdsAnc47.fa.pp"
    }

### Round 3
    call cactus_blast as blast_BirdsAnc04 {
        input: in_seq_file=seq_file, in_fa_names=["BirdsAnc08", "BirdsAnc11", "BirdsAnc06", "BirdsAnc09", "BirdsAnc07"], in_fa_files=[align_BirdsAnc08.out_fa_file, align_BirdsAnc11.out_fa_file, align_BirdsAnc06.out_fa_file, align_BirdsAnc09.out_fa_file, align_BirdsAnc07.out_fa_file], in_root="BirdsAnc04", in_config_file=config_file, out_name="BirdsAnc04.cigar"
    }
    call cactus_align as align_BirdsAnc04 {
        input: in_seq_file=seq_file, in_fa_names=["BirdsAnc08", "BirdsAnc11", "BirdsAnc06", "BirdsAnc09", "BirdsAnc07"], in_fa_files=[align_BirdsAnc08.out_fa_file, align_BirdsAnc11.out_fa_file, align_BirdsAnc06.out_fa_file, align_BirdsAnc09.out_fa_file, align_BirdsAnc07.out_fa_file], in_blast_files=blast_BirdsAnc04.out_files, in_root="BirdsAnc04", in_config_file=config_file, out_hal_name="BirdsAnc04.hal", out_fa_name="BirdsAnc04.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc10 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_907165065.1_bCapEur3.1", "GCF_000002315.5_GalGal6", "BirdsAnc16", "BirdsAnc08", "BirdsAnc11"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[0], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc16.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc11.out_fa_file], in_root="BirdsAnc10", in_config_file=config_file, out_name="BirdsAnc10.cigar"
    }
    call cactus_align as align_BirdsAnc10 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_907165065.1_bCapEur3.1", "GCF_000002315.5_GalGal6", "BirdsAnc16", "BirdsAnc08", "BirdsAnc11"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[0], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc16.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc11.out_fa_file], in_blast_files=blast_BirdsAnc10.out_files, in_root="BirdsAnc10", in_config_file=config_file, out_hal_name="BirdsAnc10.hal", out_fa_name="BirdsAnc10.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc25 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_020746105.1_bTroSur1.pri.cur", "GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc24", "BirdsAnc28"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file, align_BirdsAnc28.out_fa_file], in_root="BirdsAnc25", in_config_file=config_file, out_name="BirdsAnc25.cigar"
    }
    call cactus_align as align_BirdsAnc25 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_020746105.1_bTroSur1.pri.cur", "GCF_000002315.5_GalGal6", "BirdsAnc08", "BirdsAnc24", "BirdsAnc28"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[8], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file, align_BirdsAnc28.out_fa_file], in_blast_files=blast_BirdsAnc25.out_files, in_root="BirdsAnc25", in_config_file=config_file, out_hal_name="BirdsAnc25.hal", out_fa_name="BirdsAnc25.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc46 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_003957565.2_bTaeGut1.4.pri", "GCF_000002315.5_GalGal6", "BirdsAnc41", "BirdsAnc45", "BirdsAnc47"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file, align_BirdsAnc47.out_fa_file], in_root="BirdsAnc46", in_config_file=config_file, out_name="BirdsAnc46.cigar"
    }
    call cactus_align as align_BirdsAnc46 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_003957565.2_bTaeGut1.4.pri", "GCF_000002315.5_GalGal6", "BirdsAnc41", "BirdsAnc45", "BirdsAnc47"], in_fa_files=[preprocess_GCA_903797595_2_bEriRub2_2_GCF_003957565_2_bTae_d00e00998274d6631701ca7decbec1f5.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file, align_BirdsAnc47.out_fa_file], in_blast_files=blast_BirdsAnc46.out_files, in_root="BirdsAnc46", in_config_file=config_file, out_hal_name="BirdsAnc46.hal", out_fa_name="BirdsAnc46.fa.pp"
    }

### Round 4
    call cactus_blast as blast_BirdsAnc19 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc25", "BirdsAnc08", "BirdsAnc24", "BirdsAnc11"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc25.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file, align_BirdsAnc11.out_fa_file], in_root="BirdsAnc19", in_config_file=config_file, out_name="BirdsAnc19.cigar"
    }
    call cactus_align as align_BirdsAnc19 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc25", "BirdsAnc08", "BirdsAnc24", "BirdsAnc11"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc25.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc24.out_fa_file, align_BirdsAnc11.out_fa_file], in_blast_files=blast_BirdsAnc19.out_files, in_root="BirdsAnc19", in_config_file=config_file, out_hal_name="BirdsAnc19.hal", out_fa_name="BirdsAnc19.fa.pp"
    }

    call cactus_blast as blast_BirdsAnc42 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc41", "BirdsAnc45", "BirdsAnc38", "BirdsAnc46"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file, align_BirdsAnc38.out_fa_file, align_BirdsAnc46.out_fa_file], in_root="BirdsAnc42", in_config_file=config_file, out_name="BirdsAnc42.cigar"
    }
    call cactus_align as align_BirdsAnc42 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc41", "BirdsAnc45", "BirdsAnc38", "BirdsAnc46"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc41.out_fa_file, align_BirdsAnc45.out_fa_file, align_BirdsAnc38.out_fa_file, align_BirdsAnc46.out_fa_file], in_blast_files=blast_BirdsAnc42.out_files, in_root="BirdsAnc42", in_config_file=config_file, out_hal_name="BirdsAnc42.hal", out_fa_name="BirdsAnc42.fa.pp"
    }

### Round 5
    call cactus_blast as blast_BirdsAnc39 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc42", "BirdsAnc19", "BirdsAnc41", "BirdsAnc38"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc42.out_fa_file, align_BirdsAnc19.out_fa_file, align_BirdsAnc41.out_fa_file, align_BirdsAnc38.out_fa_file], in_root="BirdsAnc39", in_config_file=config_file, out_name="BirdsAnc39.cigar"
    }
    call cactus_align as align_BirdsAnc39 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc42", "BirdsAnc19", "BirdsAnc41", "BirdsAnc38"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc42.out_fa_file, align_BirdsAnc19.out_fa_file, align_BirdsAnc41.out_fa_file, align_BirdsAnc38.out_fa_file], in_blast_files=blast_BirdsAnc39.out_files, in_root="BirdsAnc39", in_config_file=config_file, out_hal_name="BirdsAnc39.hal", out_fa_name="BirdsAnc39.fa.pp"
    }

### Round 6
    call cactus_blast as blast_BirdsAnc37 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc39", "BirdsAnc08", "BirdsAnc38"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc39.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc38.out_fa_file], in_root="BirdsAnc37", in_config_file=config_file, out_name="BirdsAnc37.cigar"
    }
    call cactus_align as align_BirdsAnc37 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc39", "BirdsAnc08", "BirdsAnc38"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc39.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc38.out_fa_file], in_blast_files=blast_BirdsAnc37.out_files, in_root="BirdsAnc37", in_config_file=config_file, out_hal_name="BirdsAnc37.hal", out_fa_name="BirdsAnc37.fa.pp"
    }

### Round 7
    call cactus_blast as blast_BirdsAnc36 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_009829145.1_bChiLan1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc37", "BirdsAnc19", "BirdsAnc08"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc37.out_fa_file, align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file], in_root="BirdsAnc36", in_config_file=config_file, out_name="BirdsAnc36.cigar"
    }
    call cactus_align as align_BirdsAnc36 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_009829145.1_bChiLan1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc37", "BirdsAnc19", "BirdsAnc08"], in_fa_files=[preprocess_GCA_017639245_1_MMon_1_0_GCF_009829145_1_bChiLa_b454697e2f8bb95b02a95892cb242857.out_files[1], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc37.out_fa_file, align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file], in_blast_files=blast_BirdsAnc36.out_files, in_root="BirdsAnc36", in_config_file=config_file, out_hal_name="BirdsAnc36.hal", out_fa_name="BirdsAnc36.fa.pp"
    }

### Round 8
    call cactus_blast as blast_BirdsAnc33 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_016904835.1_bAcaChl1.pri", "BirdsAnc19", "BirdsAnc08", "BirdsAnc36"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[6], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc36.out_fa_file], in_root="BirdsAnc33", in_config_file=config_file, out_name="BirdsAnc33.cigar"
    }
    call cactus_align as align_BirdsAnc33 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "GCA_016904835.1_bAcaChl1.pri", "BirdsAnc19", "BirdsAnc08", "BirdsAnc36"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_020745705_1_bHemCom1_pri_cur_GCA_009769605__354fcc4d31aa2837b17dc8ad18216e11.out_files[6], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc36.out_fa_file], in_blast_files=blast_BirdsAnc33.out_files, in_root="BirdsAnc33", in_config_file=config_file, out_hal_name="BirdsAnc33.hal", out_fa_name="BirdsAnc33.fa.pp"
    }

### Round 9
    call cactus_blast as blast_BirdsAnc30 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc33", "BirdsAnc32"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc33.out_fa_file, align_BirdsAnc32.out_fa_file], in_root="BirdsAnc30", in_config_file=config_file, out_name="BirdsAnc30.cigar"
    }
    call cactus_align as align_BirdsAnc30 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc33", "BirdsAnc32"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc33.out_fa_file, align_BirdsAnc32.out_fa_file], in_blast_files=blast_BirdsAnc30.out_files, in_root="BirdsAnc30", in_config_file=config_file, out_hal_name="BirdsAnc30.hal", out_fa_name="BirdsAnc30.fa.pp"
    }

### Round 10
    call cactus_blast as blast_BirdsAnc26 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc30", "BirdsAnc29"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc30.out_fa_file, align_BirdsAnc29.out_fa_file], in_root="BirdsAnc26", in_config_file=config_file, out_name="BirdsAnc26.cigar"
    }
    call cactus_align as align_BirdsAnc26 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc30", "BirdsAnc29"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc30.out_fa_file, align_BirdsAnc29.out_fa_file], in_blast_files=blast_BirdsAnc26.out_files, in_root="BirdsAnc26", in_config_file=config_file, out_hal_name="BirdsAnc26.hal", out_fa_name="BirdsAnc26.fa.pp"
    }

### Round 11
    call cactus_blast as blast_BirdsAnc20 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819825.1_bCarCri1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc26"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[0], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc26.out_fa_file], in_root="BirdsAnc20", in_config_file=config_file, out_name="BirdsAnc20.cigar"
    }
    call cactus_align as align_BirdsAnc20 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819825.1_bCarCri1.pri", "GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc26"], in_fa_files=[preprocess_GCA_009819825_1_bCarCri1_pri_GCF_016699485_2_bG_610b10063b231ae17dced41452eff6bf.out_files[0], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc26.out_fa_file], in_blast_files=blast_BirdsAnc20.out_files, in_root="BirdsAnc20", in_config_file=config_file, out_hal_name="BirdsAnc20.hal", out_fa_name="BirdsAnc20.fa.pp"
    }

### Round 12
    call cactus_blast as blast_BirdsAnc13 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc20", "BirdsAnc11"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc20.out_fa_file, align_BirdsAnc11.out_fa_file], in_root="BirdsAnc13", in_config_file=config_file, out_name="BirdsAnc13.cigar"
    }
    call cactus_align as align_BirdsAnc13 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_000002315.5_GalGal6", "BirdsAnc19", "BirdsAnc08", "BirdsAnc20", "BirdsAnc11"], in_fa_files=[preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], align_BirdsAnc19.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc20.out_fa_file, align_BirdsAnc11.out_fa_file], in_blast_files=blast_BirdsAnc13.out_files, in_root="BirdsAnc13", in_config_file=config_file, out_hal_name="BirdsAnc13.hal", out_fa_name="BirdsAnc13.fa.pp"
    }

### Round 13
    call cactus_blast as blast_BirdsAnc05 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_016128335.1_ZJU1.0", "GCF_000002315.5_GalGal6", "GCA_009819775.1_bPhoRub2.pri", "BirdsAnc10", "BirdsAnc08", "BirdsAnc13", "BirdsAnc12", "BirdsAnc11", "BirdsAnc06", "BirdsAnc09"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[3], align_BirdsAnc10.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc13.out_fa_file, align_BirdsAnc12.out_fa_file, align_BirdsAnc11.out_fa_file, align_BirdsAnc06.out_fa_file, align_BirdsAnc09.out_fa_file], in_root="BirdsAnc05", in_config_file=config_file, out_name="BirdsAnc05.cigar"
    }
    call cactus_align as align_BirdsAnc05 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_016128335.1_ZJU1.0", "GCF_000002315.5_GalGal6", "GCA_009819775.1_bPhoRub2.pri", "BirdsAnc10", "BirdsAnc08", "BirdsAnc13", "BirdsAnc12", "BirdsAnc11", "BirdsAnc06", "BirdsAnc09"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[2], preprocess_GCA_907165065_1_bCapEur3_1_GCA_017639555_1_bCic_ca488788fbeb38dc4fea4f16efa05b17.out_files[5], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[3], align_BirdsAnc10.out_fa_file, align_BirdsAnc08.out_fa_file, align_BirdsAnc13.out_fa_file, align_BirdsAnc12.out_fa_file, align_BirdsAnc11.out_fa_file, align_BirdsAnc06.out_fa_file, align_BirdsAnc09.out_fa_file], in_blast_files=blast_BirdsAnc05.out_files, in_root="BirdsAnc05", in_config_file=config_file, out_hal_name="BirdsAnc05.hal", out_fa_name="BirdsAnc05.fa.pp"
    }

### Round 14
    call cactus_blast as blast_BirdsAnc03 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015237465.2_rCheMyd1.pri.v2", "GCA_009819545.1_rLacAgi1.alt", "GCA_016128335.1_ZJU1.0", "BirdsAnc05", "BirdsAnc04"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[2], align_BirdsAnc05.out_fa_file, align_BirdsAnc04.out_fa_file], in_root="BirdsAnc03", in_config_file=config_file, out_name="BirdsAnc03.cigar"
    }
    call cactus_align as align_BirdsAnc03 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015237465.2_rCheMyd1.pri.v2", "GCA_009819545.1_rLacAgi1.alt", "GCA_016128335.1_ZJU1.0", "BirdsAnc05", "BirdsAnc04"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[2], align_BirdsAnc05.out_fa_file, align_BirdsAnc04.out_fa_file], in_blast_files=blast_BirdsAnc03.out_files, in_root="BirdsAnc03", in_config_file=config_file, out_hal_name="BirdsAnc03.hal", out_fa_name="BirdsAnc03.fa.pp"
    }

### Round 15
    call cactus_blast as blast_BirdsAnc02 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015237465.2_rCheMyd1.pri.v2", "GCA_016128335.1_ZJU1.0", "GCA_009819545.1_rLacAgi1.alt", "BirdsAnc03"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[2], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], align_BirdsAnc03.out_fa_file], in_root="BirdsAnc02", in_config_file=config_file, out_name="BirdsAnc02.cigar"
    }
    call cactus_align as align_BirdsAnc02 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015237465.2_rCheMyd1.pri.v2", "GCA_016128335.1_ZJU1.0", "GCA_009819545.1_rLacAgi1.alt", "BirdsAnc03"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[2], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], align_BirdsAnc03.out_fa_file], in_blast_files=blast_BirdsAnc02.out_files, in_root="BirdsAnc02", in_config_file=config_file, out_hal_name="BirdsAnc02.hal", out_fa_name="BirdsAnc02.fa.pp"
    }

### Round 16
    call cactus_blast as blast_BirdsAnc01 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015237465.2_rCheMyd1.pri.v2", "GCA_009819545.1_rLacAgi1.alt", "BirdsAnc02"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], align_BirdsAnc02.out_fa_file], in_root="BirdsAnc01", in_config_file=config_file, out_name="BirdsAnc01.cigar"
    }
    call cactus_align as align_BirdsAnc01 {
        input: in_seq_file=seq_file, in_fa_names=["GCF_015237465.2_rCheMyd1.pri.v2", "GCA_009819545.1_rLacAgi1.alt", "BirdsAnc02"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[1], preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], align_BirdsAnc02.out_fa_file], in_blast_files=blast_BirdsAnc01.out_files, in_root="BirdsAnc01", in_config_file=config_file, out_hal_name="BirdsAnc01.hal", out_fa_name="BirdsAnc01.fa.pp"
    }

### Round 17
    call cactus_blast as blast_BirdsAnc00 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819545.1_rLacAgi1.alt", "BirdsAnc01"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], align_BirdsAnc01.out_fa_file], in_root="BirdsAnc00", in_config_file=config_file, out_name="BirdsAnc00.cigar"
    }
    call cactus_align as align_BirdsAnc00 {
        input: in_seq_file=seq_file, in_fa_names=["GCA_009819545.1_rLacAgi1.alt", "BirdsAnc01"], in_fa_files=[preprocess_GCA_009819545_1_rLacAgi1_alt_GCF_015237465_2_rC_f3a9fcb8c85bbcb9abe2a4691e4d061e.out_files[0], align_BirdsAnc01.out_fa_file], in_blast_files=blast_BirdsAnc00.out_files, in_root="BirdsAnc00", in_config_file=config_file, out_hal_name="out.hal", out_fa_name="BirdsAnc00.fa.pp"
    }

## HAL merging
    call hal_append_subtree as hal_append_BirdsAnc01 {
        input: in_hal_parent=align_BirdsAnc00.out_hal_file, in_hal_child=align_BirdsAnc01.out_hal_file, in_name="BirdsAnc01"
    }
    call hal_append_subtree as hal_append_BirdsAnc02 {
        input: in_hal_parent=hal_append_BirdsAnc01.out_file, in_hal_child=align_BirdsAnc02.out_hal_file, in_name="BirdsAnc02"
    }
    call hal_append_subtree as hal_append_BirdsAnc03 {
        input: in_hal_parent=hal_append_BirdsAnc02.out_file, in_hal_child=align_BirdsAnc03.out_hal_file, in_name="BirdsAnc03"
    }
    call hal_append_subtree as hal_append_BirdsAnc05 {
        input: in_hal_parent=hal_append_BirdsAnc03.out_file, in_hal_child=align_BirdsAnc05.out_hal_file, in_name="BirdsAnc05"
    }
    call hal_append_subtree as hal_append_BirdsAnc13 {
        input: in_hal_parent=hal_append_BirdsAnc05.out_file, in_hal_child=align_BirdsAnc13.out_hal_file, in_name="BirdsAnc13"
    }
    call hal_append_subtree as hal_append_BirdsAnc20 {
        input: in_hal_parent=hal_append_BirdsAnc13.out_file, in_hal_child=align_BirdsAnc20.out_hal_file, in_name="BirdsAnc20"
    }
    call hal_append_subtree as hal_append_BirdsAnc26 {
        input: in_hal_parent=hal_append_BirdsAnc20.out_file, in_hal_child=align_BirdsAnc26.out_hal_file, in_name="BirdsAnc26"
    }
    call hal_append_subtree as hal_append_BirdsAnc30 {
        input: in_hal_parent=hal_append_BirdsAnc26.out_file, in_hal_child=align_BirdsAnc30.out_hal_file, in_name="BirdsAnc30"
    }
    call hal_append_subtree as hal_append_BirdsAnc33 {
        input: in_hal_parent=hal_append_BirdsAnc30.out_file, in_hal_child=align_BirdsAnc33.out_hal_file, in_name="BirdsAnc33"
    }
    call hal_append_subtree as hal_append_BirdsAnc36 {
        input: in_hal_parent=hal_append_BirdsAnc33.out_file, in_hal_child=align_BirdsAnc36.out_hal_file, in_name="BirdsAnc36"
    }
    call hal_append_subtree as hal_append_BirdsAnc37 {
        input: in_hal_parent=hal_append_BirdsAnc36.out_file, in_hal_child=align_BirdsAnc37.out_hal_file, in_name="BirdsAnc37"
    }
    call hal_append_subtree as hal_append_BirdsAnc39 {
        input: in_hal_parent=hal_append_BirdsAnc37.out_file, in_hal_child=align_BirdsAnc39.out_hal_file, in_name="BirdsAnc39"
    }
    call hal_append_subtree as hal_append_BirdsAnc19 {
        input: in_hal_parent=hal_append_BirdsAnc39.out_file, in_hal_child=align_BirdsAnc19.out_hal_file, in_name="BirdsAnc19"
    }
    call hal_append_subtree as hal_append_BirdsAnc42 {
        input: in_hal_parent=hal_append_BirdsAnc19.out_file, in_hal_child=align_BirdsAnc42.out_hal_file, in_name="BirdsAnc42"
    }
    call hal_append_subtree as hal_append_BirdsAnc46 {
        input: in_hal_parent=hal_append_BirdsAnc42.out_file, in_hal_child=align_BirdsAnc46.out_hal_file, in_name="BirdsAnc46"
    }
    call hal_append_subtree as hal_append_BirdsAnc10 {
        input: in_hal_parent=hal_append_BirdsAnc46.out_file, in_hal_child=align_BirdsAnc10.out_hal_file, in_name="BirdsAnc10"
    }
    call hal_append_subtree as hal_append_BirdsAnc25 {
        input: in_hal_parent=hal_append_BirdsAnc10.out_file, in_hal_child=align_BirdsAnc25.out_hal_file, in_name="BirdsAnc25"
    }
    call hal_append_subtree as hal_append_BirdsAnc04 {
        input: in_hal_parent=hal_append_BirdsAnc25.out_file, in_hal_child=align_BirdsAnc04.out_hal_file, in_name="BirdsAnc04"
    }
    call hal_append_subtree as hal_append_BirdsAnc47 {
        input: in_hal_parent=hal_append_BirdsAnc04.out_file, in_hal_child=align_BirdsAnc47.out_hal_file, in_name="BirdsAnc47"
    }
    call hal_append_subtree as hal_append_BirdsAnc16 {
        input: in_hal_parent=hal_append_BirdsAnc47.out_file, in_hal_child=align_BirdsAnc16.out_hal_file, in_name="BirdsAnc16"
    }
    call hal_append_subtree as hal_append_BirdsAnc07 {
        input: in_hal_parent=hal_append_BirdsAnc16.out_file, in_hal_child=align_BirdsAnc07.out_hal_file, in_name="BirdsAnc07"
    }
    call hal_append_subtree as hal_append_BirdsAnc11 {
        input: in_hal_parent=hal_append_BirdsAnc07.out_file, in_hal_child=align_BirdsAnc11.out_hal_file, in_name="BirdsAnc11"
    }
    call hal_append_subtree as hal_append_BirdsAnc38 {
        input: in_hal_parent=hal_append_BirdsAnc11.out_file, in_hal_child=align_BirdsAnc38.out_hal_file, in_name="BirdsAnc38"
    }
    call hal_append_subtree as hal_append_BirdsAnc28 {
        input: in_hal_parent=hal_append_BirdsAnc38.out_file, in_hal_child=align_BirdsAnc28.out_hal_file, in_name="BirdsAnc28"
    }
    call hal_append_subtree as hal_append_BirdsAnc48 {
        input: in_hal_parent=hal_append_BirdsAnc28.out_file, in_hal_child=align_BirdsAnc48.out_hal_file, in_name="BirdsAnc48"
    }
    call hal_append_subtree as hal_append_BirdsAnc41 {
        input: in_hal_parent=hal_append_BirdsAnc48.out_file, in_hal_child=align_BirdsAnc41.out_hal_file, in_name="BirdsAnc41"
    }
    call hal_append_subtree as hal_append_BirdsAnc32 {
        input: in_hal_parent=hal_append_BirdsAnc41.out_file, in_hal_child=align_BirdsAnc32.out_hal_file, in_name="BirdsAnc32"
    }
    call hal_append_subtree as hal_append_BirdsAnc40 {
        input: in_hal_parent=hal_append_BirdsAnc32.out_file, in_hal_child=align_BirdsAnc40.out_hal_file, in_name="BirdsAnc40"
    }
    call hal_append_subtree as hal_append_BirdsAnc31 {
        input: in_hal_parent=hal_append_BirdsAnc40.out_file, in_hal_child=align_BirdsAnc31.out_hal_file, in_name="BirdsAnc31"
    }
    call hal_append_subtree as hal_append_BirdsAnc18 {
        input: in_hal_parent=hal_append_BirdsAnc31.out_file, in_hal_child=align_BirdsAnc18.out_hal_file, in_name="BirdsAnc18"
    }
    call hal_append_subtree as hal_append_BirdsAnc15 {
        input: in_hal_parent=hal_append_BirdsAnc18.out_file, in_hal_child=align_BirdsAnc15.out_hal_file, in_name="BirdsAnc15"
    }
    call hal_append_subtree as hal_append_BirdsAnc22 {
        input: in_hal_parent=hal_append_BirdsAnc15.out_file, in_hal_child=align_BirdsAnc22.out_hal_file, in_name="BirdsAnc22"
    }
    call hal_append_subtree as hal_append_BirdsAnc06 {
        input: in_hal_parent=hal_append_BirdsAnc22.out_file, in_hal_child=align_BirdsAnc06.out_hal_file, in_name="BirdsAnc06"
    }
    call hal_append_subtree as hal_append_BirdsAnc49 {
        input: in_hal_parent=hal_append_BirdsAnc06.out_file, in_hal_child=align_BirdsAnc49.out_hal_file, in_name="BirdsAnc49"
    }
    call hal_append_subtree as hal_append_BirdsAnc08 {
        input: in_hal_parent=hal_append_BirdsAnc49.out_file, in_hal_child=align_BirdsAnc08.out_hal_file, in_name="BirdsAnc08"
    }
    call hal_append_subtree as hal_append_BirdsAnc23 {
        input: in_hal_parent=hal_append_BirdsAnc08.out_file, in_hal_child=align_BirdsAnc23.out_hal_file, in_name="BirdsAnc23"
    }
    call hal_append_subtree as hal_append_BirdsAnc50 {
        input: in_hal_parent=hal_append_BirdsAnc23.out_file, in_hal_child=align_BirdsAnc50.out_hal_file, in_name="BirdsAnc50"
    }
    call hal_append_subtree as hal_append_BirdsAnc45 {
        input: in_hal_parent=hal_append_BirdsAnc50.out_file, in_hal_child=align_BirdsAnc45.out_hal_file, in_name="BirdsAnc45"
    }
    call hal_append_subtree as hal_append_BirdsAnc17 {
        input: in_hal_parent=hal_append_BirdsAnc45.out_file, in_hal_child=align_BirdsAnc17.out_hal_file, in_name="BirdsAnc17"
    }
    call hal_append_subtree as hal_append_BirdsAnc29 {
        input: in_hal_parent=hal_append_BirdsAnc17.out_file, in_hal_child=align_BirdsAnc29.out_hal_file, in_name="BirdsAnc29"
    }
    call hal_append_subtree as hal_append_BirdsAnc43 {
        input: in_hal_parent=hal_append_BirdsAnc29.out_file, in_hal_child=align_BirdsAnc43.out_hal_file, in_name="BirdsAnc43"
    }
    call hal_append_subtree as hal_append_BirdsAnc44 {
        input: in_hal_parent=hal_append_BirdsAnc43.out_file, in_hal_child=align_BirdsAnc44.out_hal_file, in_name="BirdsAnc44"
    }
    call hal_append_subtree as hal_append_BirdsAnc35 {
        input: in_hal_parent=hal_append_BirdsAnc44.out_file, in_hal_child=align_BirdsAnc35.out_hal_file, in_name="BirdsAnc35"
    }
    call hal_append_subtree as hal_append_BirdsAnc21 {
        input: in_hal_parent=hal_append_BirdsAnc35.out_file, in_hal_child=align_BirdsAnc21.out_hal_file, in_name="BirdsAnc21"
    }
    call hal_append_subtree as hal_append_BirdsAnc09 {
        input: in_hal_parent=hal_append_BirdsAnc21.out_file, in_hal_child=align_BirdsAnc09.out_hal_file, in_name="BirdsAnc09"
    }
    call hal_append_subtree as hal_append_BirdsAnc27 {
        input: in_hal_parent=hal_append_BirdsAnc09.out_file, in_hal_child=align_BirdsAnc27.out_hal_file, in_name="BirdsAnc27"
    }
    call hal_append_subtree as hal_append_BirdsAnc34 {
        input: in_hal_parent=hal_append_BirdsAnc27.out_file, in_hal_child=align_BirdsAnc34.out_hal_file, in_name="BirdsAnc34"
    }
    call hal_append_subtree as hal_append_BirdsAnc12 {
        input: in_hal_parent=hal_append_BirdsAnc34.out_file, in_hal_child=align_BirdsAnc12.out_hal_file, in_name="BirdsAnc12"
    }
    call hal_append_subtree as hal_append_BirdsAnc24 {
        input: in_hal_parent=hal_append_BirdsAnc12.out_file, in_hal_child=align_BirdsAnc24.out_hal_file, in_name="BirdsAnc24"
    }
    call hal_append_subtree as hal_append_BirdsAnc14 {
        input: in_hal_parent=hal_append_BirdsAnc24.out_file, in_hal_child=align_BirdsAnc14.out_hal_file, in_name="BirdsAnc14"
    }

    output {
        File out_hal = hal_append_BirdsAnc14.out_file
    }
}

