---
title: "Chr4"
author: "Iker Rivas-González"
date: "2/16/2021"
output: 
  html_document:
    code_folding: hide
---

```{r}

library(tidyverse)
library(ggthemes)
library(patchwork)
library(ggHoriPlot)

all_sp <- c(
'CALNIC_MESUNI_PHORUB_GALGAL', 'CALNIC_PHORUB_MESUNI_GALGAL', 'MESUNI_PHORUB_CALNIC_GALGAL',
'CALNIC_MESUNI_CROSUL_GALGAL', 'CALNIC_CROSUL_MESUNI_GALGAL', 'MESUNI_CROSUL_CALNIC_GALGAL',
'CALNIC_PHORUB_CROSUL_GALGAL', 'CALNIC_CROSUL_PHORUB_GALGAL', 'PHORUB_CROSUL_CALNIC_GALGAL',
'MESUNI_PHORUB_CROSUL_GALGAL', 'MESUNI_CROSUL_PHORUB_GALGAL', 'PHORUB_CROSUL_MESUNI_GALGAL') 
lookup <- setNames(LETTERS[1:length(all_sp)], all_sp)


```

```{r}

full_chr_lst <- c('1', '4')


tab_tot <- tibble()

for (spe in all_sp) {
  print(spe)
  for (chrom in full_chr_lst) {
    if (file.exists(paste0('../results/11_chr4_column_bin/info_asym/', spe, '_chr', chrom,'.csv'))) {
      # print(chrom)
      tab_tot <- read_csv(paste0('../results/11_chr4_column_bin/info_asym/', spe, '_chr', chrom,'.csv'),
                        col_types = cols(
                          position = col_double(),
                          V0 = col_double(),
                          V1 = col_double(),
                          V2 = col_double(),
                          V3 = col_double()
                        )) %>% 
      mutate(sp = spe,
             chr = chrom) %>% 
      bind_rows(tab_tot)
    }
    
  }
}

```

```{r}

tab_plt <- tab_tot %>% 
  mutate(
    sp = factor(sp, all_sp), 
    auto = ifelse(chr %in% c('Z', 'W', 'M'), chr, 'auto'),
    auto = factor(auto, c('auto', 'Z', 'W', 'M'))
    ) %>% 
  filter(auto != 'M') %>% 
  filter(auto != 'W') %>% 
  group_by(auto, sp) %>% 
  summarise_at(c('V0', 'V1', 'V2', 'V3'), sum) %>% 
  mutate(
    count = V0+V1+V2+V3,
    ILS = (V2+V3)/count
  ) %>% 
  mutate_at(c('V0', 'V1', 'V2', 'V3'), ~./count) %>% 
  pivot_longer(c(V0, V1, V2, V3)) %>% 
  rowwise() %>%
  mutate(topology = ifelse(name %in% c('V0', 'V1'),
                           paste(sort(unlist(str_split(sp, '_'))[1:2]), collapse = '_'), name),
         topology = ifelse(name %in% c('V2'),
                           paste(sort(unlist(str_split(sp, '_'))[-2][-3]), collapse = '_'), topology),
         topology = ifelse(name %in% c('V3'),
                           paste(sort(unlist(str_split(sp, '_'))[2:3]), collapse = '_'), topology)) %>% 
  mutate(
    letter = lookup[sp],
    can = ifelse(name %in% c('V0', 'V1'), 'can', name)
  )


```


```{r fig.width=15, fig.height=7}

# library(texp)
# 
# sca <- ptexp(seq(0, 1, length.out = 7), 1, 1)
sca <- c(0, 1/4, 1/3, 1/2, 2/3, 4/5, 1)
ori <- sca[4]
sca <- sca[-4]


x <- tab_tot %>% 
  mutate(
    position_2 = position+99999,
    chr = factor(chr, full_chr_lst),
    sp = factor(sp, all_sp)
  ) %>% 
  mutate(ILS = (V2+V3)/(V0+V1+V2+V3)) %>% 
  filter(chr == '4') %>% 
  group_by(sp) %>% 
  summarize(ILS_tag = as.character(round(sum(V2+V3)/sum(V0+V1+V2+V3)*100, 2)))

tab_tot %>% 
  mutate(
    position_2 = position+99999,
    chr = factor(chr, full_chr_lst),
    sp = factor(sp, all_sp)
  ) %>% 
  mutate(ILS = (V2+V3)/(V0+V1+V2+V3)) %>% 
  filter(chr == '4') %>% 
  group_by(sp) %>% 
  mutate(ILS_tag = as.character(round(sum(V2+V3)/sum(V0+V1+V2+V3)*100, 2))) -> plt_hori_all

b1 <- plt_hori_all %>% 
  filter(sp %in% all_sp[1:3]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[1:3])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0))  +
  scale_fill_hcl(palette='RdBu')

b2 <- plt_hori_all %>% 
  filter(sp %in% all_sp[4:6]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[4:6])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0)) +
  scale_fill_hcl(palette='RdBu')

b3 <- plt_hori_all %>% 
  filter(sp %in% all_sp[7:9]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[7:9])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0)) +
  scale_fill_hcl(palette='RdBu')

b4 <- plt_hori_all %>% 
  filter(sp %in% all_sp[10:12]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[10:12])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0)) +
  scale_fill_hcl(palette='RdBu')

(b1/b2/b3/b4) + plot_annotation('Chromosome 4') +
  plot_layout(guides = "collect") & guides(fill = guide_legend('ILS'))
  
ggsave('chr4_horizon_plot.pdf', width=17, height=8)

```

```{r fig.width=15, fig.height=7}

# library(texp)
# 
# sca <- ptexp(seq(0, 1, length.out = 7), 1, 1)
sca <- c(0, 1/4, 1/3, 1/2, 2/3, 4/5, 1)
ori <- sca[4]
sca <- sca[-4]


x <- tab_tot %>% 
  mutate(
    position_2 = position+99999,
    chr = factor(chr, full_chr_lst),
    sp = factor(sp, all_sp)
  ) %>% 
  mutate(ILS = (V2+V3)/(V0+V1+V2+V3)) %>% 
  filter(chr == '1') %>% 
  group_by(sp) %>% 
  summarize(ILS_tag = as.character(round(sum(V2+V3)/sum(V0+V1+V2+V3)*100, 2)))

tab_tot %>% 
  mutate(
    position_2 = position+99999,
    chr = factor(chr, full_chr_lst),
    sp = factor(sp, all_sp)
  ) %>% 
  mutate(ILS = (V2+V3)/(V0+V1+V2+V3)) %>% 
  filter(chr == '1') %>% 
  group_by(sp) %>% 
  mutate(ILS_tag = as.character(round(sum(V2+V3)/sum(V0+V1+V2+V3)*100, 2))) -> plt_hori_all

b1 <- plt_hori_all %>% 
  filter(sp %in% all_sp[1:3]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[1:3])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0))  +
  scale_fill_hcl(palette='RdBu')

b2 <- plt_hori_all %>% 
  filter(sp %in% all_sp[4:6]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[4:6])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0)) +
  scale_fill_hcl(palette='RdBu')

b3 <- plt_hori_all %>% 
  filter(sp %in% all_sp[7:9]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[7:9])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0)) +
  scale_fill_hcl(palette='RdBu')

b4 <- plt_hori_all %>% 
  filter(sp %in% all_sp[10:12]) %>% 
  ggplot() +
  stat_horizon(aes(x=position, xend=position_2, y=ILS, fill = after_stat(Cutpoints)),
               origin = ori, horizonscale = sca) +
  geom_text(aes(-5e6, 0.5, label = ILS_tag), data = filter(x, sp %in% all_sp[10:12])) +
  facet_wrap(~sp, ncol = 1, strip.position="right") +
  theme_few() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.spacing = unit(0, "lines"),
        strip.text.y = element_text(angle = 0)) +
  scale_fill_hcl(palette='RdBu') 

(b1/b2/b3/b4) + plot_annotation('Chromosome 1') +
  plot_layout(guides = "collect") & guides(fill = guide_legend('ILS'))
  
ggsave('chr1_horizon_plot.pdf', width=17, height=8)

```



```{r  fig.width=15, fig.height=7}

labels <- tab_tot %>% 
  filter(sp %in% c("CALNIC_PHORUB_CROSUL_GALGAL","CALNIC_CROSUL_PHORUB_GALGAL")) |> 
  group_by(sp, chr) |> 
  top_n(1, position) |> 
  ungroup() |> 
  select(sp, chr, position) |> 
  separate(sp, c('sp1','sp2','sp3','sp4'), remove = F) |> 
  rowwise() |> 
  mutate(
    V0 = paste0('(((', sp1, ', ', sp2, '), ', sp3, '), ', sp4, ');'),
    V1 = paste0('(((', sp1, ', ', sp2, '), ', sp3, '), ', sp4, ');'),
    V2 = paste0('(((', sp1, ', ', sp3, '), ', sp2, '), ', sp4, ');'),
    V3 = paste0('(((', sp2, ', ', sp3, '), ', sp1, '), ', sp4, ');')
  ) |> 
  select(-c(sp1, sp2, sp3, sp4)) |> 
  group_by(sp, chr, position) |> 
  pivot_longer(c(V0, V1, V2, V3)) |> 
  mutate(
    coord = as.numeric(str_remove_all(name, 'V')),
    coord = 1/5*(coord+1)
    )

plot_ribbon_tab <- tab_tot %>% 
  filter(sp %in% c("CALNIC_PHORUB_CROSUL_GALGAL","CALNIC_CROSUL_PHORUB_GALGAL")) %>%
  mutate(tot = V0+V1+V2+V3) |> 
  mutate_at(
    vars(V0, V1, V2, V3),
    ~ .x/(tot)
  ) |> 
  mutate(
    V1 = V0+V1,
    V2 = V1+V2,
    V3 = V2+V3
  ) |> 
  pivot_longer(c(V0, V1, V2, V3)) |> 
  group_by(sp, chr, position) |> 
  mutate(
    ymin = case_when(
      name == 'V0' ~ 0,
      name == 'V1' ~ value[name == 'V0'],
      name == 'V2' ~ value[name == 'V1'],
      name == 'V3' ~ value[name == 'V2'],
    ),
    ymax = case_when(
      name == 'V0' ~ value[name == 'V0'],
      name == 'V1' ~ value[name == 'V1'],
      name == 'V2' ~ value[name == 'V2'],
      name == 'V3' ~ value[name == 'V3']
    )
  )

plot_ribbon_tab |> 
  ggplot() +
  geom_line(aes(position, value, color = name)) +
  geom_ribbon(aes(x = position, ymin=ymin,ymax=ymax,  fill = name),alpha=0.5)+
  geom_text(aes(position+1000000, coord, label = value, color = name), data = labels, hjust = 0, size = 3) +
  facet_wrap(~chr+sp,scales = "free", shrink = T,ncol=1)+
  theme_classic() +
  scale_x_continuous(expand = expansion(c(0, 0.23), 0))



ggsave('ribbon_plot.pdf', width=17, height=8)


```


```{r  fig.width=15, fig.height=7}

labels <- tab_tot %>% 
  filter(sp %in% c("CALNIC_PHORUB_CROSUL_GALGAL","CALNIC_CROSUL_PHORUB_GALGAL")) |> 
  group_by(sp, chr) |> 
  top_n(1, position) |> 
  ungroup() |> 
  select(sp, chr, position) |> 
  separate(sp, c('sp1','sp2','sp3','sp4'), remove = F) |> 
  rowwise() |> 
  mutate(
    V0 = paste0('(((', sort(c(sp1, sp2))[1], ', ', sort(c(sp1, sp2))[2], '), ', sp3, '), ', sp4, ');'),
    V1 = paste0('(((', sort(c(sp1, sp2))[1], ', ', sort(c(sp1, sp2))[2], '), ', sp3, '), ', sp4, ');'),
    V2 = paste0('(((', sort(c(sp1, sp3))[1], ', ', sort(c(sp1, sp3))[2], '), ', sp2, '), ', sp4, ');'),
    V3 = paste0('(((', sort(c(sp2, sp3))[1], ', ', sort(c(sp2, sp3))[2], '), ', sp1, '), ', sp4, ');')
  ) |> 
  select(-c(sp1, sp2, sp3, sp4)) |> 
  group_by(sp, chr, position) |> 
  pivot_longer(c(V0, V1, V2, V3)) |> 
  mutate(
    coord = as.numeric(str_remove_all(name, 'V')),
    coord = 1/5*(coord+1)
    ) |> 
  rename(val = value) |> 
  ungroup()

plot_ribbon_tab <- tab_tot %>% 
  filter(sp %in% c("CALNIC_PHORUB_CROSUL_GALGAL","CALNIC_CROSUL_PHORUB_GALGAL")) %>%
  mutate(tot = V0+V1+V2+V3) |> 
  mutate_at(
    vars(V0, V1, V2, V3),
    ~ .x/(tot)
  ) |> 
  pivot_longer(c(V0, V1, V2, V3)) |> 
  full_join(select(labels, c(sp, chr, name, val)), by = c('sp', 'chr', 'name')) |> 
  ungroup() |> 
  arrange(sp, chr, position, val, name) |> 
  group_by(sp, chr, position) |> 
  mutate(
    value = cumsum(value)
  ) |> 
  mutate(
    ymin = c(0, value[1], value[2], value[3]),
    ymax = c(value[1], value[2], value[3], value[4]),
  ) 

plot_ribbon_tab |> 
  ggplot() +
  geom_line(aes(position, value, color = val, group = name, 
                linetype = ifelse(name == 'V0', 'Shallow', 'Deep'))) +
  geom_ribbon(aes(x = position, ymin=ymin,ymax=ymax,  fill = val, group = name), alpha=0.5)+
  facet_wrap(~chr+sp,scales = "free", shrink = T,ncol=1)+
  theme_classic() +
  scale_x_continuous(expand = expansion(0, 0)) +
  labs(color = 'Topology', fill = 'Topology', linetype = 'Coalescence')



ggsave('ribbon_plot_same_colors.pdf', width=17, height=8)


```

