rename "Centropus_bengalensis_Centropus_unirufus_Ceuthmochares_aereus_Crotophaga_sulcirostris_Cuculus_canorus_Geococcyx_californianus_Piaya_cayana" "allcuckoo" *
rename "Alopecoenas_beccarii" "Alopecoenas" *stat
rename "Columba_livia" "Columba" *stat
rename "Columbina_picui" "Columbina" *stat
rename "Geococcyx_californianus" "Geococcyx" *stat
rename "Patagioenas_fasciata" "Patagioenas" *stat
rename "Cuculus_canorus" "Cuculus" *stat
rename "Caloenas_nicobarica" "Caloenas" *stat
rename "Centropus_bengalensis" "Centropus_ben" *stat
rename "Centropus_unirufus" "Centropus_uni" *stat
rename "Crotophaga_sulcirostris" "Crotophaga" *stat
rename "Ceuthmochares_aereus" "Ceuthmochare" *stat
